spring:
  # servlet相关配置
  servlet:
    # 上传文件配置
    multipart:
      max-file-size: 8MB
      max-request-size: 16MB

# web容器相关配置
server:
  port: 14499

# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#data.sql.datasource
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.data-access.configure-custom-datasource
brandnewdata:
  datasource:
    schema: "test"
    url: "jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8"
    username: "root"
    password: "caiwillie"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  elasticsearch:
    uris: "http://localhost:49200"
  zeebe:
    operate:
      uri: "http://localhost:18080"

# https://github.com/camunda-community-hub/spring-zeebe/
zeebe:
  client:
    broker:
      gateway-address: "localhost:26500"
    security:
      plaintext: true

logging:
  level:
    root: INFO