spring:
  application:
    name: mop-poc

  # servlet相关配置
  servlet:
    # 上传文件配置
    multipart:
      max-file-size: 8MB
      max-request-size: 16MB

  # nacos 相关配置
  cloud:
    nacos:
      config:
        server-addr: 10.101.53.4:8848
        namespace: ${CONFIG_NAMESPACE:dev}
        group: ${CONFIG_GROUP:DEFAULT_GROUP}
        file-extension: yaml

# web容器相关配置
server:
  port: 14499

# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#data.sql.datasource
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.data-access.configure-custom-datasource
brandnewdata:
  datasource:
#    schema: "test"
#    url: "jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8"
#    username: "root"
#    password: "caiwillie"
#    driver-class-name: "com.mysql.cj.jdbc.Driver"

    schema: "mop"
    url: "jdbc:mysql://10.101.53.4:3306/mop?useUnicode=true&useSSL=false&characterEncoding=utf8"
    username: "root"
    password: "Brand@123456"
    driver-class-name: "com.mysql.cj.jdbc.Driver"


# https://github.com/camunda-community-hub/spring-zeebe/
zeebe:
  client:
    broker:
      gateway-address: "10.101.53.4:26500"
    security:
      plaintext: true