spring:
  application:
    name: modeler

  servlet: # servlet相关配置
    multipart: # 上传文件配置
      max-file-size: 8MB
      max-request-size: 16MB


# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#data.sql.datasource
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.data-access.configure-custom-datasource
brandnewdata:
  datasource:
    schema: "test"
    url: "jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8"
    username: "root"
    password: "caiwillie"
    driver-class-name: "com.mysql.cj.jdbc.Driver"


# https://github.com/camunda-community-hub/spring-zeebe/
zeebe:
  client:
    broker:
      gateway-address: "127.0.0.1:26500"
    security:
      plaintext: true