zeebe:
  client:
    worker:
      defaultName: script-worker
      defaultType: script
      threads: 3
    broker:
      gateway-address: "10.101.53.4:26500"
    job:
      timeout: 10000
    security:
      plaintext: true

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.script: DEBUG
